spring:
  datasource:
    url: jdbc:h2:mem:ecomDB
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
